name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
        version: 8
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm run -r test --coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
